### ISSUE TITLE
Enabled CORS on RapidPro Django App

### ISSUE THREAD

**Issue by royrutto-xx** [onaio/rapidpro#14]
CORS needs to be enabled to allow or Cross-Origin requests from other applications .e.g. Zebra when getting list of flows.

<img width="1279" alt="screen shot 2016-05-10 at 2 32 20 pm" src="https://cloud.githubusercontent.com/assets/1002419/15145114/6d4697a4-16bc-11e6-9435-81972f440357.png">

**Comment by pld** [comment]
@denniswambua can you do this?
