### ISSUE TITLE
Remove the Nyaruka category in organizations

### ISSUE THREAD

**Issue by ndisha** [onaio/rapidpro#3]
We currently have the organizations categorized as either in All or in Nyaruka as shown below:

<img width="1219" alt="screen shot 2015-08-05 at 5 16 00 pm" src="https://cloud.githubusercontent.com/assets/801106/9087828/b8f304f6-3b95-11e5-8afa-5b1a274189a8.png">

We don't need Nyaruka - I don't see how we will ever need this category so can we remove it?

**Comment by cafootitt** [comment]
Agree
