### ISSUE TITLE
Add link to Rapidpro docs

### ISSUE THREAD

**Issue by ndisha** [onaio/rapidpro#6]
This is also missing on our instance:

<img width="1206" alt="screen shot 2015-08-05 at 5 26 12 pm" src="https://cloud.githubusercontent.com/assets/801106/9088147/4fa45d4a-3b97-11e5-9819-791d9d414bd1.png">

Would be nice to add the link to docs on our side as well.

@denniswambua @cagulas

**Comment by cafootitt** [comment]
Yes, thanks for adding this.
