### ISSUE TITLE
Differences in users with the same rights and views 

### ISSUE THREAD

**Issue by ndisha** [onaio/rapidpro#8]
Currently, @cagulas and I don't have the admin panel in the area highlighted below:
<img width="1210" alt="screen shot 2015-08-05 at 5 34 46 pm" src="https://cloud.githubusercontent.com/assets/801106/9088403/8a232680-3b98-11e5-8771-f61b91b6a1b4.png">

while @mberg has it yet we have the same rights, as shown below:
<img width="1194" alt="screen shot 2015-08-05 at 5 38 30 pm" src="https://cloud.githubusercontent.com/assets/801106/9088469/d721e7b4-3b98-11e5-8a0b-d69e9966fe5f.png">

Might be a setting/configuration issue? @denniswambua please check this out.

**Comment by cafootitt** [comment]
Yes, creating a high priority label for this, as adding users to orgs is an important functional req.
