### ISSUE TITLE
Using a short code with Rapidpro

### ISSUE THREAD

**Issue by ndisha** [onaio/rapidpro#9]
Donard, from SNS said today that they have a short code from the largest mobile network provider in Somalia, Hormuud, which they would like to use with Rapidpro.

@denniswambua any ideas how to go about this?

**Comment by cafootitt** [comment]
Yes, also likely relevant for Bangladesh OpenSRP.  They have a short code that they've used in all of their previous mCare studies, so the population is familiar with this code and OpenSRP team would like to continue to use the same code going forward.
